In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
data=pd.read_csv("/Users/aadithyaram/Downloads/dataset.csv")

In [30]:
data.head()

track_name  popularity  speechiness  acousticness  \
0                      Comedy          73       0.1430        0.0322   
1            Ghost - Acoustic          55       0.0763        0.9240   
2              To Begin Again          57       0.0557        0.2100   
3  Can't Help Falling In Love          71       0.0363        0.9050   
4                     Hold On          82       0.0526        0.4690   

   instrumentalness  liveness  valence    tempo  time_signature track_genre  
0          0.000001    0.3580    0.715   87.917               4    acoustic  
1          0.000006    0.1010    0.267   77.489               4    acoustic  
2          0.000000    0.1170    0.120   76.332               4    acoustic  
3          0.000071    0.1320    0.143  181.740               3    acoustic  
4          0.000000    0.0829    0.167  119.949               4    acoustic

In [44]:
data1 = data.drop(['track_name'], axis=1)


In [45]:
data2=data1.drop(['track_genre'],axis=1)

In [46]:
data3=data2.drop(['artists'],axis=1)

In [47]:
import numpy as np
from sklearn.neighbors import KNeighborsRegressor

dataset = np.array([[30, 18], [40, 70], [18, 45], [60, 70], [15, 30], [90, 68], [75, 90]])
x = dataset[:, 0].reshape(-1, 1)
y = dataset[:, 1]

k = 3
knn_model = KNeighborsRegressor(n_neighbors=k)

knn_model.fit(x, y)

new_x = np.array([[25]])  
predicted_y = knn_model.predict(new_x)

print(f"Predicted y for x={new_x}: {predicted_y}")

Predicted y for x=[[25]]: [31.]


In [49]:

top_50_data = data3.head(50)
top_50_data.head()

popularity  speechiness  acousticness  instrumentalness  liveness  valence  \
0          73       0.1430        0.0322          0.000001    0.3580    0.715   
1          55       0.0763        0.9240          0.000006    0.1010    0.267   
2          57       0.0557        0.2100          0.000000    0.1170    0.120   
3          71       0.0363        0.9050          0.000071    0.1320    0.143   
4          82       0.0526        0.4690          0.000000    0.0829    0.167   

     tempo  time_signature  
0   87.917               4  
1   77.489               4  
2   76.332               4  
3  181.740               3  
4  119.949               4

In [50]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


# Split the dataset into features (X) and the target variable (y)
X = top_50_data.drop('popularity', axis=1)
y = top_50_data['popularity']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and fit a KNN classifier
k = 5  
model = KNeighborsClassifier(n_neighbors=k)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.6


In [53]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
X = top_50_data.drop('popularity', axis=1)
y = top_50_data['popularity']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create a Logistic Regression model
model = LogisticRegression()
 #Fit the model to the training data
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
("Accuracy:", accuracy)
print("\nConfusion Matrix:\n", confusion)
print("\nClassification Report:\n", classification_rep)


Confusion Matrix:
 [[6 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]]

Classification Report:
               precision    recall  f1-score   support

           0       0.60      1.00      0.75         6
           1       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         1
          62       0.00      0.00      0.00         1
          67       0.00      0.00      0.00         1

    accuracy                           0.60        10
   macro avg       0.12      0.20      0.15        10
weighted avg       0.36      0.60      0.45        10



/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_